### ISSUE TITLE
 undefined reference on Android

### ISSUE THREAD

**Issue by paul-bonnel-fr** [MarcinKulwicki/unity-native-gps-plugin#2]
Hello,

The build on Android failed due to some missing reference. Here is the stacktrace : 

The .aar is checked in my Editor. Not sure what gone wrong here. 

Thanks! 

![image](https://user-images.githubusercontent.com/33127779/159721133-a66aa644-f7fe-4b87-8301-35bdf45794b9.png)

```
Exception: Unity.IL2CPP.Building.BuilderFailedException: /Applications/Unity/Hub/Editor/2020.3.31f1/PlaybackEngines/AndroidPlayer/NDK/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ @"/var/folders/j_/y4y0k64s5jgb6xxf5msgb_g00000gn/T/tmpZdGZnX.tmp" -o "/Users/xxxxx/project/projectmobileapp/Library/il2cpp_android_arm64-v8a/il2cpp_cache/linkresult_CD8D596B9F4C0DF173ED444642069A85/libil2cpp.so" -shared -Wl,-soname,libil2cpp.so -Wl,--no-undefined -Wl,-z,noexecstack -Wl,--gc-sections -Wl,--build-id -stdlib=libc++ -static-libstdc++ -target aarch64-linux-android21 -Wl,--wrap,sigaction "/Applications/Unity/Hub/Editor/2020.3.31f1/PlaybackEngines/AndroidPlayer/Variations/il2cpp/Development/StaticLibs/arm64-v8a/baselib.a" -llog -rdynamic -fuse-ld=bfd

/Users/xxxxx/project/projectmobileapp/Library/il2cpp_android_arm64-v8a/il2cpp_cache/4A5610232FEADC6322F0C1AF701BEE23.o: In function `NativeGPSPlugin_startLocation_m111CFEAB23C3F206C6F4E4D63D94DDD601F6670A':
/Users/xxxxx/project/projectmobileapp/Library/Il2cppBuildCache/Android/arm64-v8a/il2cppOutput/Assembly-CSharp16.cpp:33248: undefined reference to `startLocation'
/Users/xxxxx/project/projectmobileapp/Library/il2cpp_android_arm64-v8a/il2cpp_cache/4A5610232FEADC6322F0C1AF701BEE23.o: In function `NativeGPSPlugin_getLongitude_m8FA328A2DEF64D7CD783F07760B5BEF07F7EA187':
/Users/xxxxx/project/projectmobileapp/Library/Il2cppBuildCache/Android/arm64-v8a/il2cppOutput/Assembly-CSharp16.cpp:33257: undefined reference to `getLongitude'
/Users/xxxxx/project/projectmobileapp/Library/il2cpp_android_arm64-v8a/il2cpp_cache/4A5610232FEADC6322F0C1AF701BEE23.o: In function `NativeGPSPlugin_getLatitude_m2AF218271DD0FB8031E7641A365B2AA7CC145FE2':
/Users/xxxxx/project/projectmobileapp/Library/Il2cppBuildCache/Android/arm64-v8a/il2cppOutput/Assembly-CSharp16.cpp:33267: undefined reference to `getLatitude'
/Users/xxxxx/project/projectmobileapp/Library/il2cpp_android_arm64-v8a/il2cpp_cache/4A5610232FEADC6322F0C1AF701BEE23.o: In function `NativeGPSPlugin_getAltitude_m01C4DD71DF70B5D5D1399B9D6B61627BC774CA48':
/Users/xxxxx/project/projectmobileapp/Library/Il2cppBuildCache/Android/arm64-v8a/il2cppOutput/Assembly-CSharp16.cpp:33277: undefined reference to `getAltitude'
/Users/xxxxx/project/projectmobileapp/Library/il2cpp_android_arm64-v8a/il2cpp_cache/4A5610232FEADC6322F0C1AF701BEE23.o: In function `NativeGPSPlugin_getAccuracy_m8A86134B8F2DB4E757539359C48913C81FF5A690':
/Users/xxxxx/project/projectmobileapp/Library/Il2cppBuildCache/Android/arm64-v8a/il2cppOutput/Assembly-CSharp16.cpp:33287: undefined reference to `getAccuracy'
/Users/xxxxx/project/projectmobileapp/Library/il2cpp_android_arm64-v8a/il2cpp_cache/4A5610232FEADC6322F0C1AF701BEE23.o: In function `NativeGPSPlugin_getVerticalAccuracyMeters_mAD2D0ADC14F5CA5A73EBEACF300193CCB8709572':
/Users/xxxxx/project/projectmobileapp/Library/Il2cppBuildCache/Android/arm64-v8a/il2cppOutput/Assembly-CSharp16.cpp:33297: undefined reference to `getVerticalAccuracyMeters'
/Users/xxxxx/project/projectmobileapp/Library/il2cpp_android_arm64-v8a/il2cpp_cache/4A5610232FEADC6322F0C1AF701BEE23.o: In function `NativeGPSPlugin_getSpeed_m76C8E170A0603E953BD2247F7F88E89EAF0B1D32':
/Users/xxxxx/project/projectmobileapp/Library/Il2cppBuildCache/Android/arm64-v8a/il2cppOutput/Assembly-CSharp16.cpp:33307: undefined reference to `getSpeed'
/Users/xxxxx/project/projectmobileapp/Library/il2cpp_android_arm64-v8a/il2cpp_cache/4A5610232FEADC6322F0C1AF701BEE23.o: In function `NativeGPSPlugin_getSpeedAccuracy_m0E9E7691818AF54630E37F54490EB73F43AEDF95':
/Users/xxxxx/project/projectmobileapp/Library/Il2cppBuildCache/Android/arm64-v8a/il2cppOutput/Assembly-CSharp16.cpp:33317: undefined reference to `getSpeedAccuracy'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)


   at Unity.IL2CPP.Building.CppProgramBuilder.PostprocessObjectFiles(HashSet`1 objectFiles, CppToolChainContext toolChainContext) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP.Building/CppProgramBuilder.cs:line 363
   at Unity.IL2CPP.Building.CppProgramBuilder.Build(IBuildStatistics& statistics) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP.Building/CppProgramBuilder.cs:line 160
   at il2cpp.Compilation.CompilationDriver.Run(RuntimePlatform platform, BuildingOptions buildingOptions, ReadOnlyCollection`1 matchedAssemblyMethodSourceFiles) in /Users/bokken/build/output/unity/il2cpp/il2cpp/Compilation/CompilationDriver.cs:line 67
   at il2cpp.Program.DoRun(String[] args, RuntimePlatform platform, BuildingOptions buildingOptions, Boolean throwExceptions) in /Users/bokken/build/output/unity/il2cpp/il2cpp/Program.cs:line 74
UnityEditorInternal.Runner.RunProgram (UnityEditor.Utils.Program p, System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildUtils.cs:129)
UnityEditorInternal.Runner.RunManagedProgram (System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser, System.Action`1[T] setupStartInfo) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildUtils.cs:65)
UnityEditorInternal.IL2CPPBuilder.RunIl2CppWithArguments (System.Collections.Generic.List`1[T] arguments, System.Action`1[T] setupStartInfo) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:818)
UnityEditorInternal.IL2CPPBuilder.ConvertPlayerDlltoCpp (UnityEditor.Il2Cpp.Il2CppBuildPipelineData data) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:785)
UnityEditorInternal.IL2CPPBuilder.Run () (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:604)
UnityEditorInternal.IL2CPPUtils.RunIl2Cpp (System.String tempFolder, System.String stagingAreaData, UnityEditorInternal.IIl2CppPlatformProvider platformProvider, System.Action`1[T] modifyOutputBeforeCompile, UnityEditor.RuntimeClassRegistry runtimeClassRegistry) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:269)
UnityEditor.Android.PostProcessor.Tasks.RunIl2Cpp.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <a40de2f63ada42c98008dd43cde35512>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <a40de2f63ada42c98008dd43cde35512>:0)
UnityEditor.Android.PostProcessAndroidPlayer.PostProcess (UnityEditor.BuildTarget target, System.String stagingAreaData, System.String stagingArea, System.String playerPackage, System.String installPath, System.String companyName, System.String productName, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <a40de2f63ada42c98008dd43cde35512>:0)
UnityEditor.Android.AndroidBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) (at <a40de2f63ada42c98008dd43cde35512>:0)
UnityEditor.PostprocessBuildPlayer.Postprocess (UnityEditor.BuildTargetGroup targetGroup, UnityEditor.BuildTarget target, System.String installPath, System.String companyName, System.String productName, System.Int32 width, System.Int32 height, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/PostprocessBuildPlayer.cs:337)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&) (at /Users/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:189)

```

**Comment by MarcinKulwicki** [comment]
Hi,

thanks for your question

This error is becouse the plugin work with Scriptiong Backed - Mono. 
For some reason don't work with IL2CPP.

I will try to fix this but I can't tell you when I will finish it.

**Comment by paul-bonnel-fr** [comment]
Hi Marcin,

Thank you for letting me know, let me know if I can help you to make it work on Android :)

**Comment by MarcinKulwicki** [comment]
Thank you for your support.

I figured out what is wrong. 

https://docs.unity3d.com/Manual/AndroidNativePlugins.html
Mono doesn't support Static library and C/C++ source files. Then when I had  
`[DllImport("__Internal")] private static extern void startLocation();` for iOS it try to take it to android project. 

<img width="741" alt="Screenshot 2022-03-23 at 17 06 03" src="https://user-images.githubusercontent.com/36818361/159745433-c9fc7180-0235-4bbd-b92b-accf57ccd13c.png">
Easy fix. Use dll only for iOS.
